export const SET_ALL_START_DATES = 'SET_ALL_START_DATES';
export const UPDATE_DATA_MONTH = 'UPDATE_DATA_MONTH';
export const UPDATE_SELECTED_DATE = 'UPDATE_SELECTED_DATE';
export const CLEAR_DATES ='CLEAR_DATES';



export const SET_DATA_MONTH = 'SET_DATA_MONTH';
export const SET_SELECTED_WEEK = 'SET_SELECTED_WEEK';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';