export const SET_ALL_START_DATES = 'SET_ALL_START_DATES';
export const UPDATE_DATA_MONTH = 'UPDATE_DATA_MONTH';
export const SET_CURRENT_HOUR ='SET_CURRENT_HOUR';
export const UPDATE_SELECTED_DATE = 'UPDATE_SELECTED_DATE';
export const CLEAR_DATES ='CLEAR_DATES';
